apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crolabkernels.crolab.io
spec:
  group: crolab.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                machineType:
                  type: string
                vcpus:
                  type: integer
                memoryMb:
                  type: integer
                userID:
                  type: string
  scope: Namespaced
  names:
    plural: crolabkernels
    singular: crolabkernel
    kind: CrolabKernel
    shortNames:
      - ckernel
