// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/proto/v1/crolab.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`     // e.g. "python:3.11-alpine"
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // e.g. "python test.py"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Zip File payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_api_proto_v1_crolab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_crolab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_crolab_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_api_proto_v1_crolab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_crolab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_crolab_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Permitir kill da operacao remotamente
	Abort         bool `protobuf:"varint,2,opt,name=abort,proto3" json:"abort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_proto_v1_crolab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_crolab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_crolab_proto_rawDescGZIP(), []int{2}
}

func (x *LogRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogRequest) GetAbort() bool {
	if x != nil {
		return x.Abort
	}
	return false
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_api_proto_v1_crolab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_crolab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_crolab_proto_rawDescGZIP(), []int{3}
}

func (x *LogMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LogMessage) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

var File_api_proto_v1_crolab_proto protoreflect.FileDescriptor

const file_api_proto_v1_crolab_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/crolab.proto\x12\tcrolab.v1\"V\n" +
	"\n" +
	"JobRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"a\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"9\n" +
	"\n" +
	"LogRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05abort\x18\x02 \x01(\bR\x05abort\"A\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError2\x89\x01\n" +
	"\rCrolabService\x12:\n" +
	"\tSubmitJob\x12\x15.crolab.v1.JobRequest\x1a\x16.crolab.v1.JobResponse\x12<\n" +
	"\n" +
	"StreamLogs\x12\x15.crolab.v1.LogRequest\x1a\x15.crolab.v1.LogMessage0\x01B%Z#github.com/crolab/core/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_crolab_proto_rawDescOnce sync.Once
	file_api_proto_v1_crolab_proto_rawDescData []byte
)

func file_api_proto_v1_crolab_proto_rawDescGZIP() []byte {
	file_api_proto_v1_crolab_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_crolab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_crolab_proto_rawDesc), len(file_api_proto_v1_crolab_proto_rawDesc)))
	})
	return file_api_proto_v1_crolab_proto_rawDescData
}

var file_api_proto_v1_crolab_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_crolab_proto_goTypes = []any{
	(*JobRequest)(nil),  // 0: crolab.v1.JobRequest
	(*JobResponse)(nil), // 1: crolab.v1.JobResponse
	(*LogRequest)(nil),  // 2: crolab.v1.LogRequest
	(*LogMessage)(nil),  // 3: crolab.v1.LogMessage
}
var file_api_proto_v1_crolab_proto_depIdxs = []int32{
	0, // 0: crolab.v1.CrolabService.SubmitJob:input_type -> crolab.v1.JobRequest
	2, // 1: crolab.v1.CrolabService.StreamLogs:input_type -> crolab.v1.LogRequest
	1, // 2: crolab.v1.CrolabService.SubmitJob:output_type -> crolab.v1.JobResponse
	3, // 3: crolab.v1.CrolabService.StreamLogs:output_type -> crolab.v1.LogMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_crolab_proto_init() }
func file_api_proto_v1_crolab_proto_init() {
	if File_api_proto_v1_crolab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_crolab_proto_rawDesc), len(file_api_proto_v1_crolab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_crolab_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_crolab_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_crolab_proto_msgTypes,
	}.Build()
	File_api_proto_v1_crolab_proto = out.File
	file_api_proto_v1_crolab_proto_goTypes = nil
	file_api_proto_v1_crolab_proto_depIdxs = nil
}
