// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.1
// source: api/proto/v1/crolab.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrolabService_SubmitJob_FullMethodName  = "/crolab.v1.CrolabService/SubmitJob"
	CrolabService_StreamLogs_FullMethodName = "/crolab.v1.CrolabService/StreamLogs"
)

// CrolabServiceClient is the client API for CrolabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrolabServiceClient interface {
	// Envia um job empacotado para o servidor
	SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	// Abre stream com o container gerado
	StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error)
}

type crolabServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrolabServiceClient(cc grpc.ClientConnInterface) CrolabServiceClient {
	return &crolabServiceClient{cc}
}

func (c *crolabServiceClient) SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, CrolabService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crolabServiceClient) StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CrolabService_ServiceDesc.Streams[0], CrolabService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrolabService_StreamLogsClient = grpc.ServerStreamingClient[LogMessage]

// CrolabServiceServer is the server API for CrolabService service.
// All implementations must embed UnimplementedCrolabServiceServer
// for forward compatibility.
type CrolabServiceServer interface {
	// Envia um job empacotado para o servidor
	SubmitJob(context.Context, *JobRequest) (*JobResponse, error)
	// Abre stream com o container gerado
	StreamLogs(*LogRequest, grpc.ServerStreamingServer[LogMessage]) error
	mustEmbedUnimplementedCrolabServiceServer()
}

// UnimplementedCrolabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrolabServiceServer struct{}

func (UnimplementedCrolabServiceServer) SubmitJob(context.Context, *JobRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedCrolabServiceServer) StreamLogs(*LogRequest, grpc.ServerStreamingServer[LogMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedCrolabServiceServer) mustEmbedUnimplementedCrolabServiceServer() {}
func (UnimplementedCrolabServiceServer) testEmbeddedByValue()                       {}

// UnsafeCrolabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrolabServiceServer will
// result in compilation errors.
type UnsafeCrolabServiceServer interface {
	mustEmbedUnimplementedCrolabServiceServer()
}

func RegisterCrolabServiceServer(s grpc.ServiceRegistrar, srv CrolabServiceServer) {
	// If the following call panics, it indicates UnimplementedCrolabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrolabService_ServiceDesc, srv)
}

func _CrolabService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrolabServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrolabService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrolabServiceServer).SubmitJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrolabService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CrolabServiceServer).StreamLogs(m, &grpc.GenericServerStream[LogRequest, LogMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrolabService_StreamLogsServer = grpc.ServerStreamingServer[LogMessage]

// CrolabService_ServiceDesc is the grpc.ServiceDesc for CrolabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrolabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crolab.v1.CrolabService",
	HandlerType: (*CrolabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _CrolabService_SubmitJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _CrolabService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/crolab.proto",
}
